# REST API

### Root Test
GET http://localhost:3000/

### About
GET http://localhost:3000/about

### Gect All Profile
GET http://localhost:3000/profile

### Create New Profile
POST http://localhost:3000/profile
Content-Type: application/json

{
  "username": "demo",
  "password": "1234",
  "mobile": "088888888",
  "cardId": "1123456789101"
}
